name: flutter_practice
description: "新しいFlutterプロジェクトです。"
# 次の行は、このパッケージが `flutter pub publish` を使用して
# pub.dev に誤って公開されるのを防ぎます。
# これはプライベートパッケージに推奨されます。
publish_to: 'none' # pub.devに公開したい場合、この行を削除してください。

# 以下は、アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は、1.2.43 のようにドットで区切られた3つの数字で構成され、
# オプションで + で区切られたビルド番号が続きます。
# バージョンとビルド番号は、それぞれ `flutter build` コマンドで
# --build-name と --build-number を指定することで上書きできます。
# Androidでは、build-nameはversionNameとして使用され、
# build-numberはversionCodeとして使用されます。
# Androidのバージョン管理についての詳細は以下を参照してください：
# https://developer.android.com/studio/publish/versioning
# iOSでは、build-nameはCFBundleShortVersionStringとして使用され、
# build-numberはCFBundleVersionとして使用されます。
# iOSのバージョン管理についての詳細は以下を参照してください：
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windowsでは、build-nameは製品およびファイルバージョンの
# メジャー、マイナー、パッチ部分として使用され、
# build-numberはビルドサフィックスとして使用されます。
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# 依存関係は、このパッケージが動作するために必要な他のパッケージを指定します。
# 依存関係を最新バージョンに自動的にアップグレードするには、
# `flutter pub upgrade --major-versions` を実行してください。
# または、以下のバージョン番号を手動で変更して、
# pub.devで利用可能な最新バージョンに更新することもできます。
# 新しいバージョンが利用可能な依存関係を確認するには、
# `flutter pub outdated` を実行してください。
dependencies:
  flutter:
    sdk: flutter

  # 次の行は、Cupertino Icons フォントをアプリケーションに追加します。
  # iOSスタイルのアイコンを使用するためにCupertinoIconsクラスと一緒に使用します。
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 以下の "flutter_lints" パッケージには、良いコーディング習慣を促進するための
  # 推奨されるリントセットが含まれています。
  # このパッケージが提供するリントセットは、パッケージのルートにある
  # `analysis_options.yaml` ファイルで有効化されています。
  # 特定のリントルールを無効化したり、追加のルールを有効化したりする方法については、
  # このファイルを参照してください。
  flutter_lints: ^5.0.0

# このファイルの一般的なDart部分に関する情報は、以下のページを参照してください：
# https://dart.dev/tools/pub/pubspec

# 以下のセクションはFlutterパッケージに特有のものです。
flutter:

  # 次の行は、Material Icons フォントがアプリケーションに含まれることを保証します。
  # これにより、Material Icons クラスのアイコンを使用できます。
  uses-material-design: true

  # アセットをアプリケーションに追加するには、以下のようにアセットセクションを追加します：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 画像アセットは、1つ以上の解像度固有の「バリアント」を参照できます。
  # 詳細は以下を参照してください：
  # https://flutter.dev/to/resolution-aware-images

  # パッケージ依存関係からアセットを追加する方法についての詳細は、
  # 以下を参照してください：
  # https://flutter.dev/to/asset-from-package

  # カスタムフォントをアプリケーションに追加するには、この "flutter" セクション内に
  # フォントセクションを追加します。このリスト内の各エントリには、
  # フォントファミリ名を指定する "family" キーと、
  # フォントのアセットやその他の記述子を指定する "fonts" キーが必要です。
  # 例：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存関係からフォントを追加する方法についての詳細は、
  # 以下を参照してください：
  # https://flutter.dev/to/font-from-package
